/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProgram"];
        put: operations["updateProgram"];
        post?: never;
        delete: operations["deleteProgram"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/teachers/{teacherId}/compensation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upsertTeacherCompensation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/enrollments/{enrollmentId}/teacher-assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assignTeacher"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/sepay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handleSepayWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher/bookings/{bookingId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentPurchases"];
        put?: never;
        post: operations["createStudentPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{quizId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startQuizAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz-attempts/{attemptId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitQuizAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrograms"];
        put?: never;
        post: operations["createProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{programId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProgramLessons"];
        put?: never;
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLessonVideo"];
        put?: never;
        post: operations["upsertLessonVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/video/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncLessonVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/video-upload-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLessonVideoUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/video-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLessonVideoProgress"];
        put?: never;
        post: operations["updateLessonVideoProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLessonQuiz"];
        put?: never;
        post: operations["upsertLessonQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluator/checkpoint-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitCheckpointResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enrollStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeachers"];
        put?: never;
        post: operations["createTeacher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudents"];
        put?: never;
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/purchases/{id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markPurchasePaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/evaluators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvaluators"];
        put?: never;
        post: operations["createEvaluator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/checkpoint-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckpointSessions"];
        put?: never;
        post: operations["createCheckpointSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/checkpoint-sessions/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addCheckpointParticipants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete: operations["deleteLesson"];
        options?: never;
        head?: never;
        patch: operations["updateLesson"];
        trace?: never;
    };
    "/api/enrollments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateEnrollmentStatus"];
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/admin/enrollments/{id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["extendEnrollment"];
        trace?: never;
    };
    "/api/admin/checkpoint-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckpointSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCheckpointSession"];
        trace?: never;
    };
    "/api/admin/checkpoint-sessions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCheckpointSessionStatus"];
        trace?: never;
    };
    "/api/teacher/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/teacher-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/purchases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentPurchase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/checkpoint-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckpointStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicPrograms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicProgram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/video-playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLessonVideoPlayback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lessonId}/learning-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLessonLearningState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluator/checkpoint-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckpointSessions_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluator/checkpoint-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckpointSession_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/teachers/{teacherId}/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/teachers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacher"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentEnrollments_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminPurchases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/checkpoint-eligible-students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckpointEligibleStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/checkpoint-sessions/{id}/participants/{participantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeCheckpointParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateProgramRequest: {
            name: string;
            description?: string;
            price?: number;
            currency?: string;
            salesStatus?: string;
        };
        ProgramResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            price?: number;
            currency?: string;
            salesStatus?: string;
        };
        UpsertTeacherCompensationRequest: {
            amountPerSession: number;
            currency?: string;
        };
        TeacherCompensationResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            teacherId?: number;
            amountPerSession?: number;
            currency?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AssignTeacherRequest: {
            /** Format: int64 */
            teacherId: number;
        };
        TeacherAssignmentResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            enrollmentId?: number;
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            /** Format: int64 */
            programId?: number;
            programName?: string;
            /** Format: int64 */
            teacherId?: number;
            teacherName?: string;
            /** Format: date-time */
            assignedAt?: string;
        };
        SepayWebhookResponse: {
            success?: boolean;
        };
        ReviewBookingRequest: {
            result: string;
            comment?: string;
        };
        TeacherBookingResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            /** Format: int64 */
            teacherId?: number;
            teacherName?: string;
            /** Format: int64 */
            enrollmentId?: number;
            /** Format: int64 */
            lessonId?: number;
            lessonName?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TeacherEarningResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            teacherId?: number;
            /** Format: int64 */
            bookingId?: number;
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            /** Format: int64 */
            lessonId?: number;
            lessonName?: string;
            amount?: number;
            currency?: string;
            status?: string;
            /** Format: date-time */
            earnedAt?: string;
        };
        TeacherReviewResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            bookingId?: number;
            result?: string;
            comment?: string;
            /** Format: date-time */
            reviewedAt?: string;
            booking?: components["schemas"]["TeacherBookingResponse"];
            earning?: components["schemas"]["TeacherEarningResponse"];
        };
        CreateAvailabilityRequest: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        TeacherAvailabilityResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            teacherId?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreatePurchaseRequest: {
            /** Format: int64 */
            programId: number;
        };
        PurchaseResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            studentEmail?: string;
            /** Format: int64 */
            programId?: number;
            programName?: string;
            amount?: number;
            currency?: string;
            status?: string;
            paymentCode?: string;
            paymentQrUrl?: string;
            paymentProvider?: string;
            paymentContent?: string;
            /** Format: int64 */
            enrollmentId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            paidAt?: string;
        };
        CreateBookingRequest: {
            /** Format: int64 */
            lessonId: number;
            /** Format: date-time */
            slotStartAt: string;
        };
        QuizAttemptResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            quizId?: number;
            /** Format: int64 */
            lessonId?: number;
            /** Format: int64 */
            studentId?: number;
            /** Format: int32 */
            attemptNumber?: number;
            submitted?: boolean;
            /** Format: int32 */
            correctCount?: number;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            scorePercent?: number;
            /** Format: int32 */
            bestScorePercent?: number;
            lessonProgressStatus?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
        };
        SubmitQuizAnswerRequest: {
            /** Format: int64 */
            questionId: number;
            /** Format: int64 */
            selectedOptionId: number;
        };
        SubmitQuizAttemptRequest: {
            answers: components["schemas"]["SubmitQuizAnswerRequest"][];
        };
        CreateLessonRequest: {
            name: string;
            /** Format: int32 */
            lessonNumber?: number;
            content?: string;
        };
        LessonResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            programId?: number;
            name?: string;
            /** Format: int32 */
            lessonNumber?: number;
            content?: string;
            status?: string;
            lessonProgressStatus?: string;
            locked?: boolean;
        };
        UpsertLessonVideoRequest: {
            bunnyVideoId: string;
            libraryId: string;
            /** Format: int32 */
            durationSeconds?: number;
            thumbnailUrl?: string;
            status?: string;
        };
        LessonVideoResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            lessonId?: number;
            bunnyVideoId?: string;
            libraryId?: string;
            /** Format: int32 */
            durationSeconds?: number;
            thumbnailUrl?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateVideoUploadSessionRequest: {
            title?: string;
            fileType: string;
        };
        VideoUploadSessionResponse: {
            /** Format: int64 */
            lessonId?: number;
            /** Format: int64 */
            lessonVideoId?: number;
            videoId?: string;
            libraryId?: string;
            tusUploadUrl?: string;
            authorizationSignature?: string;
            /** Format: int64 */
            authorizationExpire?: number;
            title?: string;
            fileType?: string;
            status?: string;
        };
        UpdateVideoProgressRequest: {
            /** Format: int32 */
            currentSecond?: number;
            /** Format: int32 */
            furthestWatchedSecond?: number;
        };
        VideoProgressResponse: {
            /** Format: int64 */
            lessonId?: number;
            /** Format: int64 */
            lessonVideoId?: number;
            /** Format: int32 */
            currentSecond?: number;
            /** Format: int32 */
            furthestWatchedSecond?: number;
            /** Format: int32 */
            watchedPercentage?: number;
            completed?: boolean;
            lessonProgressStatus?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        QuizOptionRequest: {
            optionText: string;
            correct?: boolean;
        };
        QuizQuestionRequest: {
            questionText: string;
            options: components["schemas"]["QuizOptionRequest"][];
        };
        UpsertQuizRequest: {
            title: string;
            questions: components["schemas"]["QuizQuestionRequest"][];
        };
        QuizOptionResponse: {
            /** Format: int64 */
            id?: number;
            optionText?: string;
            /** Format: int32 */
            position?: number;
            correct?: boolean;
        };
        QuizQuestionResponse: {
            /** Format: int64 */
            id?: number;
            questionText?: string;
            /** Format: int32 */
            position?: number;
            options?: components["schemas"]["QuizOptionResponse"][];
        };
        QuizResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            lessonId?: number;
            title?: string;
            questions?: components["schemas"]["QuizQuestionResponse"][];
        };
        SubmitCheckpointResultRequest: {
            /** Format: int64 */
            participantId: number;
            result: string;
            comment?: string;
        };
        CheckpointResultResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            participantId?: number;
            /** Format: int64 */
            evaluatorId?: number;
            result?: string;
            comment?: string;
            /** Format: date-time */
            evaluatedAt?: string;
        };
        EnrollStudentRequest: {
            /** Format: int64 */
            studentId: number;
            /** Format: int64 */
            programId: number;
        };
        EnrollmentResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            studentId?: number;
            /** Format: int64 */
            programId?: number;
            status?: string;
            /** Format: date-time */
            enrolledAt?: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        RegisterStudentRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
        };
        StudentProfileResponse: {
            /** Format: int64 */
            userId?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            status?: string;
            mustChangePassword?: boolean;
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        LoginResponse: {
            accessToken?: string;
            refreshToken?: string;
            mustChangePassword?: boolean;
        };
        LoginRequest: {
            username?: string;
            password?: string;
        };
        ChangePasswordRequest: {
            oldPassword?: string;
            newPassword?: string;
        };
        CreateTeacherRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
            bio?: string;
        };
        TeacherProfileResponse: {
            /** Format: int64 */
            userId?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            bio?: string;
        };
        CreateStudentRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
        };
        CreateEvaluatorRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
        };
        EvaluatorProfileResponse: {
            /** Format: int64 */
            userId?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
        };
        CreateCheckpointSessionRequest: {
            /** Format: int64 */
            programId: number;
            /** Format: int32 */
            blockNumber: number;
            /** Format: int64 */
            evaluatorId: number;
            /** Format: date-time */
            scheduledAt: string;
            meetLink: string;
            participantEnrollmentIds?: number[];
        };
        CheckpointParticipantResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            enrollmentId?: number;
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            /** Format: date-time */
            addedAt?: string;
            result?: components["schemas"]["CheckpointResultResponse"];
        };
        CheckpointSessionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            checkpointId?: number;
            /** Format: int64 */
            programId?: number;
            programName?: string;
            /** Format: int32 */
            blockNumber?: number;
            /** Format: int32 */
            startLessonNumber?: number;
            /** Format: int32 */
            gateLessonNumber?: number;
            /** Format: int32 */
            nextLessonNumber?: number;
            /** Format: int64 */
            evaluatorId?: number;
            evaluatorName?: string;
            /** Format: date-time */
            scheduledAt?: string;
            meetLink?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            participants?: components["schemas"]["CheckpointParticipantResponse"][];
        };
        AddCheckpointParticipantsRequest: {
            enrollmentIds: number[];
        };
        UpdateLessonRequest: {
            name: string;
            /** Format: int32 */
            lessonNumber?: number;
            content?: string;
        };
        UpdateEnrollmentRequest: {
            status: string;
        };
        UpdateUserRequest: {
            /** Format: email */
            email?: string;
            enabled?: boolean;
            status?: string;
        };
        AccountAccessResponse: {
            /** Format: int64 */
            userId?: number;
            status?: string;
            mustChangePassword?: boolean;
            /** Format: date-time */
            firstLoginAt?: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            enabled?: boolean;
            role?: string;
            studentProfile?: components["schemas"]["StudentProfileResponse"];
            teacherProfile?: components["schemas"]["TeacherProfileResponse"];
            evaluatorProfile?: components["schemas"]["EvaluatorProfileResponse"];
            accountAccess?: components["schemas"]["AccountAccessResponse"];
        };
        ExtendEnrollmentRequest: {
            /** Format: int32 */
            months: number;
        };
        UpdateCheckpointSessionRequest: {
            /** Format: int64 */
            evaluatorId?: number;
            /** Format: date-time */
            scheduledAt?: string;
            meetLink?: string;
        };
        UpdateCheckpointSessionStatusRequest: {
            status: string;
        };
        TeacherSlotResponse: {
            /** Format: int64 */
            teacherId?: number;
            teacherName?: string;
            /** Format: int64 */
            availabilityId?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
        };
        StudentCheckpointStatusResponse: {
            /** Format: int64 */
            lessonId?: number;
            lessonProgressStatus?: string;
            /** Format: int64 */
            checkpointId?: number;
            /** Format: int64 */
            sessionId?: number;
            /** Format: int64 */
            participantId?: number;
            /** Format: int64 */
            programId?: number;
            programName?: string;
            /** Format: int32 */
            blockNumber?: number;
            /** Format: int32 */
            gateLessonNumber?: number;
            /** Format: int32 */
            nextLessonNumber?: number;
            sessionStatus?: string;
            /** Format: date-time */
            scheduledAt?: string;
            meetLink?: string;
            /** Format: int64 */
            evaluatorId?: number;
            evaluatorName?: string;
            lastResult?: string;
            lastComment?: string;
            /** Format: date-time */
            lastEvaluatedAt?: string;
        };
        PageResponseProgramResponse: {
            content?: components["schemas"]["ProgramResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        VideoPlaybackResponse: {
            /** Format: int64 */
            lessonId?: number;
            /** Format: int64 */
            lessonVideoId?: number;
            playbackUrl?: string;
            /** Format: int32 */
            durationSeconds?: number;
            thumbnailUrl?: string;
            status?: string;
        };
        LearningStateResponse: {
            /** Format: int64 */
            lessonId?: number;
            lessonStatus?: string;
            videoStatus?: string;
            progress?: components["schemas"]["VideoProgressSnapshot"];
            quizAvailable?: boolean;
            hasQuiz?: boolean;
            enrollmentStatus?: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        VideoProgressSnapshot: {
            /** Format: int32 */
            currentSecond?: number;
            /** Format: int32 */
            furthestWatchedSecond?: number;
            /** Format: int32 */
            watchedPercentage?: number;
            completed?: boolean;
            lessonProgressStatus?: string;
        };
        AdminTeacherResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            bio?: string;
            enabled?: boolean;
            status?: string;
        };
        PageResponseAdminTeacherResponse: {
            content?: components["schemas"]["AdminTeacherResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        TeacherEarningsSummaryResponse: {
            /** Format: int64 */
            teacherId?: number;
            totalEarned?: number;
            currency?: string;
            earnings?: components["schemas"]["TeacherEarningResponse"][];
        };
        AdminStudentResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            enabled?: boolean;
            status?: string;
        };
        PageResponseAdminStudentResponse: {
            content?: components["schemas"]["AdminStudentResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        AdminEnrollmentResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            studentEmail?: string;
            /** Format: int64 */
            programId?: number;
            programName?: string;
            status?: string;
            /** Format: date-time */
            enrolledAt?: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        PageResponsePurchaseResponse: {
            content?: components["schemas"]["PurchaseResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        AdminEvaluatorResponse: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            enabled?: boolean;
            status?: string;
        };
        PageResponseAdminEvaluatorResponse: {
            content?: components["schemas"]["AdminEvaluatorResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        PageResponseAdminEnrollmentResponse: {
            content?: components["schemas"]["AdminEnrollmentResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        PageResponseCheckpointSessionResponse: {
            content?: components["schemas"]["CheckpointSessionResponse"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        CheckpointEligibleStudentResponse: {
            /** Format: int64 */
            studentId?: number;
            studentName?: string;
            /** Format: int64 */
            enrollmentId?: number;
            /** Format: int64 */
            programId?: number;
            programName?: string;
            /** Format: int32 */
            blockNumber?: number;
            /** Format: int32 */
            startLessonNumber?: number;
            /** Format: int32 */
            gateLessonNumber?: number;
            /** Format: int32 */
            nextLessonNumber?: number;
            /** Format: int64 */
            gateLessonId?: number;
            gateLessonName?: string;
            /** Format: date-time */
            eligibleAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgramResponse"];
                };
            };
        };
    };
    updateProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProgramRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgramResponse"];
                };
            };
        };
    };
    deleteProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsertTeacherCompensation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacherId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTeacherCompensationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherCompensationResponse"];
                };
            };
        };
    };
    assignTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollmentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignTeacherRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherAssignmentResponse"];
                };
            };
        };
    };
    handleSepayWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-SePay-Signature"?: string;
                "X-SePay-Timestamp"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SepayWebhookResponse"];
                };
            };
        };
    };
    reviewBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBookingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherReviewResponse"];
                };
            };
        };
    };
    createAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherAvailabilityResponse"];
                };
            };
        };
    };
    getStudentPurchases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseResponse"][];
                };
            };
        };
    };
    createStudentPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseResponse"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherBookingResponse"];
                };
            };
        };
    };
    startQuizAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuizAttemptResponse"];
                };
            };
        };
    };
    submitQuizAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitQuizAttemptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuizAttemptResponse"];
                };
            };
        };
    };
    getPrograms: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseProgramResponse"];
                };
            };
        };
    };
    createProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProgramRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgramResponse"];
                };
            };
        };
    };
    getProgramLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonResponse"][];
                };
            };
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLessonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    getLessonVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonVideoResponse"];
                };
            };
        };
    };
    upsertLessonVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertLessonVideoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonVideoResponse"];
                };
            };
        };
    };
    syncLessonVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonVideoResponse"];
                };
            };
        };
    };
    createLessonVideoUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVideoUploadSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VideoUploadSessionResponse"];
                };
            };
        };
    };
    getLessonVideoProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VideoProgressResponse"];
                };
            };
        };
    };
    updateLessonVideoProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVideoProgressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VideoProgressResponse"];
                };
            };
        };
    };
    getLessonQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuizResponse"];
                };
            };
        };
    };
    upsertLessonQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertQuizRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuizResponse"];
                };
            };
        };
    };
    publishLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    submitCheckpointResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCheckpointResultRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointResultResponse"];
                };
            };
        };
    };
    enrollStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnrollmentResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentProfileResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTeachers: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminTeacherResponse"];
                };
            };
        };
    };
    createTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeacherRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherProfileResponse"];
                };
            };
        };
    };
    getStudents: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminStudentResponse"];
                };
            };
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentProfileResponse"];
                };
            };
        };
    };
    markPurchasePaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseResponse"];
                };
            };
        };
    };
    getEvaluators: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminEvaluatorResponse"];
                };
            };
        };
    };
    createEvaluator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluatorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EvaluatorProfileResponse"];
                };
            };
        };
    };
    getCheckpointSessions: {
        parameters: {
            query?: {
                programId?: number;
                blockNumber?: number;
                status?: string;
                weekStart?: string;
                weekEnd?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCheckpointSessionResponse"];
                };
            };
        };
    };
    createCheckpointSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckpointSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
    addCheckpointParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCheckpointParticipantsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    deleteLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLessonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LessonResponse"];
                };
            };
        };
    };
    updateEnrollmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEnrollmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnrollmentResponse"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    extendEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendEnrollmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnrollmentResponse"];
                };
            };
        };
    };
    getCheckpointSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
    updateCheckpointSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCheckpointSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
    updateCheckpointSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCheckpointSessionStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
    getTeacherStudents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherAssignmentResponse"][];
                };
            };
        };
    };
    getTeacherBookings: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherBookingResponse"][];
                };
            };
        };
    };
    getTeacherSlots: {
        parameters: {
            query: {
                lessonId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherSlotResponse"][];
                };
            };
        };
    };
    getStudentPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseResponse"];
                };
            };
        };
    };
    getStudentEnrollments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnrollmentResponse"][];
                };
            };
        };
    };
    getCheckpointStatus: {
        parameters: {
            query: {
                lessonId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentCheckpointStatusResponse"];
                };
            };
        };
    };
    getPublicPrograms: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseProgramResponse"];
                };
            };
        };
    };
    getPublicProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgramResponse"];
                };
            };
        };
    };
    getLessonVideoPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VideoPlaybackResponse"];
                };
            };
        };
    };
    getLessonLearningState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningStateResponse"];
                };
            };
        };
    };
    getCheckpointSessions_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"][];
                };
            };
        };
    };
    getCheckpointSession_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getTeacherEarnings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacherId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeacherEarningsSummaryResponse"];
                };
            };
        };
    };
    getTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTeacherResponse"];
                };
            };
        };
    };
    getStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminStudentResponse"];
                };
            };
        };
    };
    getStudentEnrollments_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminEnrollmentResponse"][];
                };
            };
        };
    };
    getAdminPurchases: {
        parameters: {
            query?: {
                studentId?: string;
                programId?: string;
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponsePurchaseResponse"];
                };
            };
        };
    };
    getAdminEnrollments: {
        parameters: {
            query?: {
                studentId?: string;
                programId?: string;
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminEnrollmentResponse"];
                };
            };
        };
    };
    getCheckpointEligibleStudents: {
        parameters: {
            query?: {
                programId?: number;
                blockNumber?: number;
                weekStart?: string;
                weekEnd?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointEligibleStudentResponse"][];
                };
            };
        };
    };
    removeCheckpointParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                participantId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckpointSessionResponse"];
                };
            };
        };
    };
}
